-- ─────────────────────────────────────────────────────────────────────────────
-- seed_anchors.sql — CCTR anchor / suppressor / modifier rows.
-- ─────────────────────────────────────────────────────────────────────────────
--
-- This file is the curated, hand-authored complement to seed_keywords_v2.sql
-- (which is generated by TF-IDF). Every row here is one of three classes that
-- the legacy pipeline did not have:
--
--   anchor      A token that is dispositive for one chapter. Weight near 1.0.
--               The CCTR rebalancer treats anchor rows as sticky (won't lower
--               below 0.9), so an anchor stays an anchor even after retuning.
--               Examples:  'm16 rifle' (ch93), 'lithium-ion battery' (ch85),
--                          'tea bags' (ch09 — note this resolves the failing
--                          "Tea, bags" → electronics regression).
--
--   suppressor  Negative evidence for the row's chapter. When matched, the
--               score for that chapter goes DOWN. This is how compliance-
--               sensitive overlaps stop the wrong chapter from winning when
--               the right one would otherwise lose to a single signal hit.
--               Examples:  'military-grade' suppresses ch95 (toys);
--                          'toy' suppresses ch93 (arms).
--
--   modifier    Context shifter — when matched, retypes signals across
--               chapters listed in `notes` as `targets:ch{NN},ch{NN}`. The
--               `notes` directive is parsed by load_keywords_typed in
--               classifier.py at /reload time; everything else in `notes` is
--               free-text justification.
--               Examples:  'toy' modifier targets ch95 (so 'gun', 'tank',
--                          'helicopter' get retyped from ch93/87/88 to ch95
--                          before per-chapter scoring).
--
-- Coverage: the chapters this file covers are the ones that surface most
-- often in the failing 99-row regression set — 95, 93, 87, 88, 28, 29, 30,
-- 09. Other chapters get anchor coverage as failures are discovered.
--
-- Rules of the road (CCTR plan §5c, governance):
--   1. Every row must declare `signal_class` (no defaults — make it explicit).
--   2. Every row must have a `notes` value with the owner/ticket/rationale
--      OR (for modifiers) the `targets:` directive. CI checks this.
--   3. New rows MUST land with a corresponding pinned test in
--      ml-service/tests/test_collisions.py before merge.
--
-- Safe to re-run: ON CONFLICT (category_id, hs_chapter, keyword, signal_class)
-- DO NOTHING targets the partial unique index `uniq_category_keywords_cctr`.
-- ─────────────────────────────────────────────────────────────────────────────


-- ── ch95 — toys ──────────────────────────────────────────────────────────────
-- Anchors: textbook toy nouns that should never be misread as machinery / arms.
-- Suppressors: signals that, if present, mean the shipment is NOT a toy
--   (military-grade lithium battery, real ammunition, etc.).
-- Modifiers: 'toy', 'plush', 'lego', 'nerf' retype defense/automotive/aircraft
--   tokens to ch95.  Without these, "toy gun" would score in ch93.
INSERT INTO category_keywords (category_id, hs_chapter, keyword, weight, signal_class, source, notes)
SELECT cc.id, v.hs, v.kw, v.wt, v.cls, 'manual', v.note
FROM   classification_categories cc, (VALUES
    -- anchors
    ('95', 'plush toy',          1.0, 'anchor',     'CCTR-001 chapter-defining toy noun'),
    ('95', 'doll',                1.0, 'anchor',     'CCTR-001 chapter-defining toy noun'),
    ('95', 'board game',          1.0, 'anchor',     'CCTR-001 chapter-defining toy noun'),
    ('95', 'jigsaw puzzle',       1.0, 'anchor',     'CCTR-001 chapter-defining toy noun'),
    ('95', 'building block set',  1.0, 'anchor',     'CCTR-001 chapter-defining toy noun'),
    ('95', 'tricycle',            1.0, 'anchor',     'CCTR-001 chapter-defining toy noun'),
    ('95', 'rocking horse',       1.0, 'anchor',     'CCTR-001 chapter-defining toy noun'),
    ('95', 'sporting goods',      0.95,'anchor',     'CCTR-001 ch95 covers sporting requisites per HS title'),
    -- suppressors (would be a real-weapon / industrial-battery shipment)
    ('95', 'military-grade',      1.0, 'suppressor', 'CCTR-002 negates ch95 in toy/military overlap'),
    ('95', 'mil-spec',            1.0, 'suppressor', 'CCTR-002 negates ch95 in toy/military overlap'),
    ('95', 'live-fire',           1.0, 'suppressor', 'CCTR-002 real ammo signal'),
    ('95', 'industrial battery',  0.7, 'suppressor', 'CCTR-002 industrial cells are not toy parts'),
    ('95', 'tactical',            0.7, 'suppressor', 'CCTR-002 tactical signals defense not play'),
    -- modifiers — retype defense/auto/aircraft tokens INTO ch95
    ('95', 'toy',                 1.0, 'modifier',   'targets:ch95 — retypes gun/tank/helicopter/aircraft/car/truck to toys'),
    ('95', 'plush',               1.0, 'modifier',   'targets:ch95 — soft-toy variant of `toy`'),
    ('95', 'nerf',                1.0, 'modifier',   'targets:ch95 — Hasbro brand modifier; retypes gun→toy'),
    ('95', 'lego',                1.0, 'modifier',   'targets:ch95 — block-toy modifier; retypes vehicle/aircraft/gun'),
    ('95', 'rc',                  0.8, 'modifier',   'targets:ch95 — RC = remote-control hobby toy'),
    ('95', 'scale model',         1.0, 'modifier',   'targets:ch95 — scale-model toy modifier'),
    ('95', 'kids',                0.6, 'modifier',   'targets:ch95 — weak modifier; intentional, alone insufficient')
) AS v(hs, kw, wt, cls, note)
WHERE cc.name = 'toys'
ON CONFLICT (category_id, hs_chapter, keyword, signal_class) WHERE hs_chapter IS NOT NULL DO NOTHING;


-- ── ch93 — defense (arms and ammunition) ─────────────────────────────────────
-- Anchors: real weapons / ammunition signal words that *only* live in ch93.
-- Suppressors: 'toy', 'plastic toy', 'lego' make a defense classification
--   wrong even if 'gun' or 'rifle' is present.
INSERT INTO category_keywords (category_id, hs_chapter, keyword, weight, signal_class, source, notes)
SELECT cc.id, v.hs, v.kw, v.wt, v.cls, 'manual', v.note
FROM   classification_categories cc, (VALUES
    -- anchors
    ('93', 'm16 rifle',          1.0, 'anchor',     'CCTR-003 ch93 anchor — military firearm model'),
    ('93', 'ak-47',              1.0, 'anchor',     'CCTR-003 ch93 anchor — military firearm model'),
    ('93', '5.56mm',             1.0, 'anchor',     'CCTR-003 ch93 anchor — NATO live-fire calibre'),
    ('93', '7.62mm',             1.0, 'anchor',     'CCTR-003 ch93 anchor — NATO/WP live-fire calibre'),
    ('93', '9mm',                0.9, 'anchor',     'CCTR-003 ch93 anchor — pistol calibre'),
    ('93', 'live ammunition',    1.0, 'anchor',     'CCTR-003 ch93 anchor'),
    ('93', 'cartridge',          0.9, 'anchor',     'CCTR-003 ch93 anchor'),
    ('93', 'firearm',            1.0, 'anchor',     'CCTR-003 ch93 anchor — generic real-arm'),
    ('93', 'sidearm',            0.95,'anchor',     'CCTR-003 ch93 anchor'),
    ('93', 'rocket launcher',    1.0, 'anchor',     'CCTR-003 ch93 anchor — heavy weapon'),
    ('93', 'grenade',            1.0, 'anchor',     'CCTR-003 ch93 anchor — explosive ordnance'),
    -- suppressors (a "toy gun" in ch93 should drop)
    ('93', 'toy',                1.0, 'suppressor', 'CCTR-004 toy negates real-arm classification'),
    ('93', 'plastic toy',        1.0, 'suppressor', 'CCTR-004 toy material variant'),
    ('93', 'nerf',               1.0, 'suppressor', 'CCTR-004 brand-specific toy negation'),
    ('93', 'lego',               1.0, 'suppressor', 'CCTR-004 brand-specific toy negation'),
    -- modifiers — retype ambiguous tokens INTO ch93 when present
    ('93', 'military',           1.0, 'modifier',   'targets:ch93 — retypes gun/tank/helicopter to defense'),
    ('93', 'military-grade',     1.0, 'modifier',   'targets:ch93 — retypes gun/tank/helicopter to defense'),
    ('93', 'tactical',           0.9, 'modifier',   'targets:ch93 — retypes ambiguous arms terms to defense')
) AS v(hs, kw, wt, cls, note)
WHERE cc.name = 'defense'
ON CONFLICT (category_id, hs_chapter, keyword, signal_class) WHERE hs_chapter IS NOT NULL DO NOTHING;


-- ── ch87 — automotive ────────────────────────────────────────────────────────
-- Anchors: real-vehicle signals that should never resolve to toys/aircraft.
-- Suppressors: 'toy car' should NOT be ch87.
INSERT INTO category_keywords (category_id, hs_chapter, keyword, weight, signal_class, source, notes)
SELECT cc.id, v.hs, v.kw, v.wt, v.cls, 'manual', v.note
FROM   classification_categories cc, (VALUES
    -- anchors
    ('87', 'passenger car',      1.0, 'anchor',     'CCTR-005 ch87 anchor — full-size automobile'),
    ('87', 'sedan',              0.95,'anchor',     'CCTR-005 ch87 anchor'),
    ('87', 'suv',                0.95,'anchor',     'CCTR-005 ch87 anchor'),
    ('87', 'pickup truck',       1.0, 'anchor',     'CCTR-005 ch87 anchor'),
    ('87', 'commercial vehicle', 1.0, 'anchor',     'CCTR-005 ch87 anchor'),
    ('87', 'engine block',       0.9, 'anchor',     'CCTR-005 ch87 anchor — automotive part'),
    ('87', 'brake pad',          0.9, 'anchor',     'CCTR-005 ch87 anchor — automotive part'),
    ('87', 'clutch assembly',    0.9, 'anchor',     'CCTR-005 ch87 anchor — automotive part'),
    ('87', 'transmission',       0.85,'anchor',     'CCTR-005 ch87 anchor — automotive part'),
    ('87', 'tyre',               0.9, 'anchor',     'CCTR-005 ch87 anchor — pneumatic tyre'),
    ('87', 'tire',               0.9, 'anchor',     'CCTR-005 ch87 anchor — pneumatic tyre (US)'),
    ('87', 'oem part',           0.85,'anchor',     'CCTR-005 ch87 anchor — OEM auto part'),
    -- suppressors (toy car / model car should NOT be ch87)
    ('87', 'toy',                0.9, 'suppressor', 'CCTR-006 retypes "toy car" away from ch87'),
    ('87', 'scale model',        0.9, 'suppressor', 'CCTR-006 model car != real car'),
    ('87', 'rc',                 0.7, 'suppressor', 'CCTR-006 RC car suppresses real-auto')
) AS v(hs, kw, wt, cls, note)
WHERE cc.name = 'automotive'
ON CONFLICT (category_id, hs_chapter, keyword, signal_class) WHERE hs_chapter IS NOT NULL DO NOTHING;


-- ── ch88 — aircraft (under machinery category) ──────────────────────────────
-- Anchors: real-aircraft signals.
-- Suppressors: 'toy helicopter' should not resolve to ch88.
INSERT INTO category_keywords (category_id, hs_chapter, keyword, weight, signal_class, source, notes)
SELECT cc.id, v.hs, v.kw, v.wt, v.cls, 'manual', v.note
FROM   classification_categories cc, (VALUES
    -- anchors
    ('88', 'commercial aircraft',1.0, 'anchor',     'CCTR-007 ch88 anchor'),
    ('88', 'turbojet engine',    1.0, 'anchor',     'CCTR-007 ch88 anchor — aviation propulsion'),
    ('88', 'turbofan',           1.0, 'anchor',     'CCTR-007 ch88 anchor'),
    ('88', 'fuselage',           1.0, 'anchor',     'CCTR-007 ch88 anchor — aircraft structure'),
    ('88', 'avionics',           1.0, 'anchor',     'CCTR-007 ch88 anchor'),
    ('88', 'rotorcraft',         1.0, 'anchor',     'CCTR-007 ch88 anchor — helicopter family'),
    ('88', 'spacecraft',         1.0, 'anchor',     'CCTR-007 ch88 anchor'),
    -- suppressors
    ('88', 'toy',                0.9, 'suppressor', 'CCTR-008 toy helicopter is not aircraft'),
    ('88', 'rc',                 0.7, 'suppressor', 'CCTR-008 RC helicopter is hobby ch95'),
    ('88', 'scale model',        0.9, 'suppressor', 'CCTR-008 model aircraft is hobby ch95')
) AS v(hs, kw, wt, cls, note)
WHERE cc.name = 'machinery'
ON CONFLICT (category_id, hs_chapter, keyword, signal_class) WHERE hs_chapter IS NOT NULL DO NOTHING;


-- ── ch28 / ch29 — chemicals ──────────────────────────────────────────────────
-- Anchors for distinctive inorganic / organic chemistry; helps "Chemical
-- products, nos" land in chemicals when no HS code is supplied.
INSERT INTO category_keywords (category_id, hs_chapter, keyword, weight, signal_class, source, notes)
SELECT cc.id, v.hs, v.kw, v.wt, v.cls, 'manual', v.note
FROM   classification_categories cc, (VALUES
    -- ch28 — inorganic
    ('28', 'sulphuric acid',     1.0, 'anchor',     'CCTR-009 ch28 anchor — inorganic acid'),
    ('28', 'sulfuric acid',      1.0, 'anchor',     'CCTR-009 ch28 anchor — US spelling'),
    ('28', 'hydrochloric acid',  1.0, 'anchor',     'CCTR-009 ch28 anchor'),
    ('28', 'sodium hydroxide',   1.0, 'anchor',     'CCTR-009 ch28 anchor — caustic soda'),
    ('28', 'caustic soda',       1.0, 'anchor',     'CCTR-009 ch28 anchor'),
    ('28', 'nitric acid',        1.0, 'anchor',     'CCTR-009 ch28 anchor'),
    ('28', 'ammonia',            0.9, 'anchor',     'CCTR-009 ch28 anchor'),
    ('28', 'chlorine gas',       1.0, 'anchor',     'CCTR-009 ch28 anchor'),
    -- ch29 — organic
    ('29', 'methanol',           1.0, 'anchor',     'CCTR-010 ch29 anchor — organic alcohol'),
    ('29', 'ethanol industrial', 1.0, 'anchor',     'CCTR-010 ch29 anchor — denatured ethanol'),
    ('29', 'acetone',            1.0, 'anchor',     'CCTR-010 ch29 anchor'),
    ('29', 'toluene',            1.0, 'anchor',     'CCTR-010 ch29 anchor'),
    ('29', 'benzene',            1.0, 'anchor',     'CCTR-010 ch29 anchor'),
    ('29', 'formaldehyde',       1.0, 'anchor',     'CCTR-010 ch29 anchor'),
    ('29', 'glycerin',           0.9, 'anchor',     'CCTR-010 ch29 anchor — polyol'),
    ('29', 'ethylene glycol',    1.0, 'anchor',     'CCTR-010 ch29 anchor')
) AS v(hs, kw, wt, cls, note)
WHERE cc.name = 'chemicals'
ON CONFLICT (category_id, hs_chapter, keyword, signal_class) WHERE hs_chapter IS NOT NULL DO NOTHING;


-- ── ch30 — pharmaceuticals ───────────────────────────────────────────────────
-- Anchors for drug-product nouns that should beat the chemicals/cosmetics tail.
INSERT INTO category_keywords (category_id, hs_chapter, keyword, weight, signal_class, source, notes)
SELECT cc.id, v.hs, v.kw, v.wt, v.cls, 'manual', v.note
FROM   classification_categories cc, (VALUES
    ('30', 'vaccine',            1.0, 'anchor',     'CCTR-011 ch30 anchor — biologic'),
    ('30', 'insulin',            1.0, 'anchor',     'CCTR-011 ch30 anchor — biologic'),
    ('30', 'antibiotic',         1.0, 'anchor',     'CCTR-011 ch30 anchor'),
    ('30', 'tablet',             0.7, 'anchor',     'CCTR-011 ch30 anchor — dosage form'),
    ('30', 'capsule',            0.7, 'anchor',     'CCTR-011 ch30 anchor — dosage form'),
    ('30', 'sterile injection',  1.0, 'anchor',     'CCTR-011 ch30 anchor'),
    ('30', 'api pharmaceutical', 1.0, 'anchor',     'CCTR-011 ch30 anchor — active ingredient'),
    ('30', 'syringe sterile',    0.95,'anchor',     'CCTR-011 ch30 anchor — sterile medical device'),
    -- suppressor: cosmetics overlap
    ('30', 'cosmetic',           0.7, 'suppressor', 'CCTR-012 cosmetic claim suppresses drug ch30')
) AS v(hs, kw, wt, cls, note)
WHERE cc.name = 'pharmaceuticals'
ON CONFLICT (category_id, hs_chapter, keyword, signal_class) WHERE hs_chapter IS NOT NULL DO NOTHING;


-- ── ch09 — coffee, tea, mate, spices (food_beverages) ────────────────────────
-- Single most impactful anchor set: 'tea' anchored in ch09 fixes the
-- "Tea, bags" → electronics regression (SID 50) and prevents 'tea' from
-- ever scoring electronics through 'bag' keyword overlap.
INSERT INTO category_keywords (category_id, hs_chapter, keyword, weight, signal_class, source, notes)
SELECT cc.id, v.hs, v.kw, v.wt, v.cls, 'manual', v.note
FROM   classification_categories cc, (VALUES
    ('09', 'tea',                1.0, 'anchor',     'CCTR-013 ch09 anchor — fixes "Tea, bags" → electronics regression'),
    ('09', 'tea bags',           1.0, 'anchor',     'CCTR-013 ch09 anchor — phrase match'),
    ('09', 'green tea',          1.0, 'anchor',     'CCTR-013 ch09 anchor'),
    ('09', 'black tea',          1.0, 'anchor',     'CCTR-013 ch09 anchor'),
    ('09', 'coffee',             1.0, 'anchor',     'CCTR-013 ch09 anchor'),
    ('09', 'coffee beans',       1.0, 'anchor',     'CCTR-013 ch09 anchor'),
    ('09', 'cardamom',           1.0, 'anchor',     'CCTR-013 ch09 anchor — spice'),
    ('09', 'turmeric',           1.0, 'anchor',     'CCTR-013 ch09 anchor — spice'),
    ('09', 'cinnamon',           1.0, 'anchor',     'CCTR-013 ch09 anchor — spice'),
    ('09', 'black pepper',       1.0, 'anchor',     'CCTR-013 ch09 anchor — spice')
) AS v(hs, kw, wt, cls, note)
WHERE cc.name = 'food_beverages'
ON CONFLICT (category_id, hs_chapter, keyword, signal_class) WHERE hs_chapter IS NOT NULL DO NOTHING;


-- ── ch85 — electronics: lithium-ion anchor + toy battery suppressor ──────────
-- The plan's headline polysemy fix: 'battery' alone is a signal across many
-- chapters, but 'lithium-ion battery' is a real-electronics anchor. The
-- toy-side handles the inverse via the 'toy' modifier in ch95.
INSERT INTO category_keywords (category_id, hs_chapter, keyword, weight, signal_class, source, notes)
SELECT cc.id, v.hs, v.kw, v.wt, v.cls, 'manual', v.note
FROM   classification_categories cc, (VALUES
    ('85', 'lithium-ion battery',1.0, 'anchor',     'CCTR-014 ch85 anchor — real-electronics battery'),
    ('85', 'lithium ion battery',1.0, 'anchor',     'CCTR-014 ch85 anchor — alternate spelling'),
    ('85', 'li-ion cell',        1.0, 'anchor',     'CCTR-014 ch85 anchor'),
    ('85', 'pcb assembly',       1.0, 'anchor',     'CCTR-014 ch85 anchor — printed circuit'),
    ('85', 'semiconductor wafer',1.0, 'anchor',     'CCTR-014 ch85 anchor'),
    ('85', 'integrated circuit', 1.0, 'anchor',     'CCTR-014 ch85 anchor'),
    -- suppressors: toy-battery, AAA-pack should NOT swamp ch85 when toy modifier fires
    ('85', 'toy',                0.7, 'suppressor', 'CCTR-015 toy modifier suppresses ch85 battery'),
    ('85', 'plush',              0.6, 'suppressor', 'CCTR-015 plush-toy battery is hobby ch95'),
    -- modifier on the chemicals/cosmetics overlap: 'industrial-grade' affirms ch85
    ('85', 'industrial-grade',   0.7, 'modifier',   'targets:ch85 — affirms electronics for industrial battery shipments')
) AS v(hs, kw, wt, cls, note)
WHERE cc.name = 'electronics'
ON CONFLICT (category_id, hs_chapter, keyword, signal_class) WHERE hs_chapter IS NOT NULL DO NOTHING;
