-- Seed 20 shipment classification categories.
-- Safe to re-run (ON CONFLICT DO NOTHING).
INSERT INTO classification_categories (name, display_name, description, is_active) VALUES
    ('electronics',      'Electronics & Components',         'PCBs, semiconductors, consumer electronics, cables, batteries, displays', true),
    ('perishables',      'Perishable Goods',                 'Temperature-sensitive goods requiring cold chain: seafood, dairy, fresh produce', true),
    ('chemicals',        'Chemicals & Hazardous Materials',  'Industrial chemicals, solvents, acids, hazmat goods, MSDS-regulated cargo', true),
    ('textiles',         'Textiles & Apparel',               'Fabrics, garments, yarn, footwear, woven and knitted materials', true),
    ('machinery',        'Industrial Machinery & Equipment', 'Heavy equipment, industrial tools, turbines, compressors, conveyors', true),
    ('pharmaceuticals',  'Pharmaceuticals & Medical Devices','Drugs, vaccines, APIs, surgical instruments, sterile medical equipment', true),
    ('automotive',       'Automotive Parts & Vehicles',      'Vehicles, spare parts, tyres, engines, gearboxes, OEM components', true),
    ('food_beverages',   'Food & Beverages',                 'Packaged food, beverages, condiments, snacks, canned and bottled goods', true),
    ('furniture',        'Furniture & Home Goods',           'Household furniture, mattresses, decor items, bedding, upholstery', true),
    ('plastics',         'Plastics & Rubber',                'Raw plastic resin, rubber goods, polymers, elastomers, HDPE/PVC/PP products', true),
    ('metals',           'Metals & Metal Products',          'Steel, aluminium, copper, iron, alloys, pipes, bars, sheet metal, coils', true),
    ('paper',            'Paper & Printing Materials',       'Paper rolls, cardboard, corrugated sheets, printed matter, kraft paper', true),
    ('minerals',         'Minerals & Mining Products',       'Ores, limestone, granite, aggregates, sand, gravel, coal, bauxite', true),
    ('energy',           'Energy & Fuel Products',           'Crude oil, petroleum, LNG, LPG, diesel, lubricants, fuel, kerosene', true),
    ('agriculture',      'Agricultural Products',            'Grains, wheat, corn, fertilizers, pesticides, seeds, livestock, cotton', true),
    ('cosmetics',        'Cosmetics & Personal Care',        'Skincare, makeup, perfume, shampoo, toiletries, sunscreen, fragrances', true),
    ('toys',             'Toys & Sporting Goods',            'Toys, dolls, board games, bicycles, sports equipment, playground gear', true),
    ('construction',     'Construction Materials',           'Cement, timber, rebar, bricks, glass, roofing, insulation, plywood', true),
    ('defense',          'Defense & Security Equipment',     'Military hardware, surveillance equipment, tactical gear, ammunition', true),
    ('luxury',           'Luxury Goods & Jewelry',           'Watches, jewelry, diamonds, gold, designer handbags, luxury apparel', true)
ON CONFLICT (name) DO NOTHING;

-- 96 HS 2-digit chapters → 20 coarse categories.
-- Every active chapter (01..97, excluding 77 which is WCO-reserved) is
-- assigned to exactly one category. is_primary flags the anchor chapters;
-- "false" marks pragmatic absorptions explained in results/taxonomy_notes.md.
INSERT INTO category_hs_chapters (category_id, hs_chapter, chapter_title, is_primary)
SELECT cc.id, v.hs_chapter, v.chapter_title, v.is_primary
FROM   classification_categories cc
JOIN (VALUES
    ('agriculture', '01', 'Live animals', false),
    ('perishables', '02', 'Meat and edible meat offal', true),
    ('perishables', '03', 'Fish, crustaceans, molluscs and other aquatic invertebrates', true),
    ('food_beverages', '04', 'Dairy produce; birds'' eggs; natural honey', true),
    ('agriculture', '05', 'Products of animal origin, not elsewhere specified', false),
    ('agriculture', '06', 'Live trees and other plants; bulbs, cut flowers', true),
    ('perishables', '07', 'Edible vegetables and certain roots and tubers', true),
    ('perishables', '08', 'Edible fruit and nuts; peel of citrus fruit or melons', true),
    ('food_beverages', '09', 'Coffee, tea, mate and spices', true),
    ('agriculture', '10', 'Cereals', true),
    ('food_beverages', '11', 'Products of the milling industry; malt; starches', true),
    ('agriculture', '12', 'Oil seeds and oleaginous fruits; miscellaneous grains, seeds and fruit', true),
    ('agriculture', '13', 'Lac; gums, resins and other vegetable saps and extracts', false),
    ('agriculture', '14', 'Vegetable plaiting materials; vegetable products not elsewhere specified', true),
    ('food_beverages', '15', 'Animal or vegetable fats and oils and their cleavage products', true),
    ('food_beverages', '16', 'Preparations of meat, fish, crustaceans, molluscs or other aquatic invertebrates', true),
    ('food_beverages', '17', 'Sugars and sugar confectionery', true),
    ('food_beverages', '18', 'Cocoa and cocoa preparations', true),
    ('food_beverages', '19', 'Preparations of cereals, flour, starch or milk; pastrycooks'' products', true),
    ('food_beverages', '20', 'Preparations of vegetables, fruit, nuts or other parts of plants', true),
    ('food_beverages', '21', 'Miscellaneous edible preparations', true),
    ('food_beverages', '22', 'Beverages, spirits and vinegar', true),
    ('agriculture', '23', 'Residues and waste from the food industries; prepared animal fodder', true),
    ('food_beverages', '24', 'Tobacco and manufactured tobacco substitutes', false),
    ('construction', '25', 'Salt; sulphur; earths and stone; plastering materials, lime and cement', true),
    ('minerals', '26', 'Ores, slag and ash', true),
    ('energy', '27', 'Mineral fuels, mineral oils and products of their distillation', true),
    ('chemicals', '28', 'Inorganic chemicals; organic or inorganic compounds of precious metals', true),
    ('chemicals', '29', 'Organic chemicals', true),
    ('pharmaceuticals', '30', 'Pharmaceutical products', true),
    ('chemicals', '31', 'Fertilizers', true),
    ('chemicals', '32', 'Tanning or dyeing extracts; dyes, pigments, paints and varnishes', true),
    ('cosmetics', '33', 'Essential oils and resinoids; perfumery, cosmetic or toilet preparations', true),
    ('chemicals', '34', 'Soap, organic surface-active agents, washing preparations, lubricants', true),
    ('chemicals', '35', 'Albuminoidal substances; modified starches; glues; enzymes', true),
    ('chemicals', '36', 'Explosives; pyrotechnic products; matches; pyrophoric alloys', false),
    ('electronics', '37', 'Photographic or cinematographic goods', false),
    ('chemicals', '38', 'Miscellaneous chemical products', true),
    ('plastics', '39', 'Plastics and articles thereof', true),
    ('plastics', '40', 'Rubber and articles thereof', true),
    ('agriculture', '41', 'Raw hides and skins (other than furskins) and leather', false),
    ('luxury', '42', 'Articles of leather; saddlery and harness; travel goods, handbags', false),
    ('luxury', '43', 'Furskins and artificial fur; manufactures thereof', false),
    ('construction', '44', 'Wood and articles of wood; wood charcoal', false),
    ('construction', '45', 'Cork and articles of cork', false),
    ('furniture', '46', 'Manufactures of straw, esparto or other plaiting materials; basketware', false),
    ('paper', '47', 'Pulp of wood or of other fibrous cellulosic material; recovered waste paper', true),
    ('paper', '48', 'Paper and paperboard; articles of paper pulp, of paper or of paperboard', true),
    ('paper', '49', 'Printed books, newspapers, pictures and other products of the printing industry', true),
    ('textiles', '50', 'Silk', true),
    ('textiles', '51', 'Wool, fine or coarse animal hair; horsehair yarn and woven fabric', true),
    ('textiles', '52', 'Cotton', true),
    ('textiles', '53', 'Other vegetable textile fibres; paper yarn and woven fabrics of paper yarn', true),
    ('textiles', '54', 'Man-made filaments; strip and the like of man-made textile materials', true),
    ('textiles', '55', 'Man-made staple fibres', true),
    ('textiles', '56', 'Wadding, felt and nonwovens; special yarns; twine, cordage, ropes and cables', true),
    ('textiles', '57', 'Carpets and other textile floor coverings', true),
    ('textiles', '58', 'Special woven fabrics; tufted textile fabrics; lace; tapestries; trimmings; embroidery', true),
    ('textiles', '59', 'Impregnated, coated, covered or laminated textile fabrics', true),
    ('textiles', '60', 'Knitted or crocheted fabrics', true),
    ('textiles', '61', 'Articles of apparel and clothing accessories, knitted or crocheted', true),
    ('textiles', '62', 'Articles of apparel and clothing accessories, not knitted or crocheted', true),
    ('textiles', '63', 'Other made-up textile articles; sets; worn clothing; rags', true),
    ('textiles', '64', 'Footwear, gaiters and the like; parts of such articles', false),
    ('textiles', '65', 'Headgear and parts thereof', false),
    ('textiles', '66', 'Umbrellas, sun umbrellas, walking sticks, whips, riding-crops', false),
    ('textiles', '67', 'Prepared feathers and down; artificial flowers; articles of human hair', false),
    ('construction', '68', 'Articles of stone, plaster, cement, asbestos, mica or similar materials', true),
    ('construction', '69', 'Ceramic products', true),
    ('construction', '70', 'Glass and glassware', true),
    ('luxury', '71', 'Natural or cultured pearls, precious or semi-precious stones, precious metals, jewelry', true),
    ('metals', '72', 'Iron and steel', true),
    ('metals', '73', 'Articles of iron or steel', true),
    ('metals', '74', 'Copper and articles thereof', true),
    ('metals', '75', 'Nickel and articles thereof', true),
    ('metals', '76', 'Aluminium and articles thereof', true),
    ('metals', '78', 'Lead and articles thereof', true),
    ('metals', '79', 'Zinc and articles thereof', true),
    ('metals', '80', 'Tin and articles thereof', true),
    ('metals', '81', 'Other base metals; cermets; articles thereof', true),
    ('metals', '82', 'Tools, implements, cutlery, spoons and forks, of base metal', false),
    ('metals', '83', 'Miscellaneous articles of base metal', false),
    ('machinery', '84', 'Nuclear reactors, boilers, machinery and mechanical appliances', true),
    ('electronics', '85', 'Electrical machinery and equipment; sound and television recorders', true),
    ('machinery', '86', 'Railway or tramway locomotives, rolling stock and parts thereof', false),
    ('automotive', '87', 'Vehicles other than railway or tramway rolling stock, and parts and accessories thereof', true),
    ('machinery', '88', 'Aircraft, spacecraft, and parts thereof', false),
    ('machinery', '89', 'Ships, boats and floating structures', false),
    ('pharmaceuticals', '90', 'Optical, photographic, measuring, checking, precision, medical or surgical instruments', false),
    ('luxury', '91', 'Clocks and watches and parts thereof', false),
    ('toys', '92', 'Musical instruments; parts and accessories of such articles', false),
    ('defense', '93', 'Arms and ammunition; parts and accessories thereof', true),
    ('furniture', '94', 'Furniture; bedding, mattresses, lighting', true),
    ('toys', '95', 'Toys, games and sports requisites; parts and accessories thereof', true),
    ('toys', '96', 'Miscellaneous manufactured articles', false),
    ('luxury', '97', 'Works of art, collectors'' pieces and antiques', false)
) AS v(category_name, hs_chapter, chapter_title, is_primary)
    ON cc.name = v.category_name
ON CONFLICT (category_id, hs_chapter) DO NOTHING;
